baseURI=http://localhost:3000
kafkaBootstrapServers=localhost:9092
kafkaClientEventsTopic=client-events
kafkaAccountEventsTopic=account-events
kafkaPortfolioEventsTopic=portfolio-events
kafkaTransactionEventsTopic=transaction-events
kafkaConsumerTimeoutMs=10000
kafkaPollIntervalMs=500
kafkaConsumerGroupPrefix=ai-kafka-validator-tests
username=user1
password=password1
authEndPoint=/auth/login
allClientsEndPoint=/clients
clientEndPoint=/clients/{clientId}
allAccountsEndPoint=/accounts
accountEndPoint=/accounts/{clientId}
allTransactionsEndPoint=/transactions
transactionEndPoint=/transactions/{clientId}
allPortfoliosEndPoint=/portfolios
portfolioEndPoint=/portfolios/{clientId}
