version: '3.8'
services:
  json-server:
    image: my-json-server
    ports:
      - "3000:3000"
  rest-assured-api-tests:
    build: .
    depends_on:
      - json-server

#version: '3.8'
#services:
#  json-server:
#    image: vedeshenkov/my-json-server:latest
#    ports:
#      - "3000:3000"
#  rest-assured-api-tests:
#    build: .
#    depends_on:
#      - json-server


