package com.analysis.onboarding;

import com.analysis.onboarding.model.EnvironmentCheck;
import com.analysis.onboarding.model.EnvironmentReport;
import com.analysis.onboarding.model.ProjectChunk;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

public class SetupOnboardingService {
    private static final String FULL_SUITE_COMMAND = "sh ./mvnw clean test -Dtestng.suite.file=testng.xml -DbaseURI=http://localhost:3000 -DkafkaBootstrapServers=localhost:9092 -DkafkaClientEventsTopic=client-events -DkafkaAccountEventsTopic=account-events -DkafkaPortfolioEventsTopic=portfolio-events -DkafkaTransactionEventsTopic=transaction-events";
    private static final String SERVER_START_COMMAND = """
            cd server
            npm install
            KAFKA_BOOTSTRAP_SERVERS=localhost:9092 \\
            KAFKA_CLIENT_EVENTS_TOPIC=client-events \\
            KAFKA_ACCOUNT_EVENTS_TOPIC=account-events \\
            KAFKA_PORTFOLIO_EVENTS_TOPIC=portfolio-events \\
            KAFKA_TRANSACTION_EVENTS_TOPIC=transaction-events \\
            npm start
            """;

    private final Path projectRoot;
    private final RetrievalService retrievalService;
    private final EnvironmentCheckService environmentCheckService;

    public SetupOnboardingService(Path projectRoot, List<ProjectChunk> chunks) {
        this.projectRoot = projectRoot;
        this.retrievalService = new RetrievalService(chunks);
        this.environmentCheckService = new EnvironmentCheckService();
    }

    public String answer(String question) {
        QuestionIntent intent = QuestionIntent.classify(question);
        List<ProjectChunk> chunks = retrievalService.retrieve(question, 6);
        EnvironmentReport environmentReport = needsEnvironmentChecks(intent)
                ? environmentCheckService.runBasicChecks(projectRoot)
                : null;

        return switch (intent) {
            case QUICK_START -> buildSetupAnswer(
                    "Use Docker for the fastest end-to-end demo, or use the hybrid local path if you want to inspect the Node server and Kafka interactions directly.",
                    List.of(
                            codeBlock("bash", "docker compose up --build --abort-on-container-exit --exit-code-from api-tests"),
                            codeBlock("bash", "docker compose -f docker-compose.kafka.yml up -d"),
                            codeBlock("bash", SERVER_START_COMMAND),
                            codeBlock("bash", FULL_SUITE_COMMAND)
                    ),
                    chunks,
                    environmentReport,
                    List.of(
                            "Reports are generated by the Maven run, not by `npm start`.",
                            "For hybrid local execution, the server process and the Java test run both need to point to `localhost:9092`."
                    ),
                    "If you want a guided walkthrough, ask: `What is the fastest demo flow to show?`"
            );
            case DOCKER_SETUP -> buildSetupAnswer(
                    "Use the main Compose file when you want Kafka, the mock API, and the Java tests to run together in one command.",
                    List.of(
                            codeBlock("bash", "docker compose up --build --abort-on-container-exit --exit-code-from api-tests"),
                            codeBlock("bash", "docker compose down -v")
                    ),
                    chunks,
                    environmentReport,
                    List.of(
                            "`docker-compose.yml` is the full-stack entrypoint, while `docker-compose.kafka.yml` is intentionally kept for Kafka-only hybrid local execution.",
                            "If reports are missing after a Docker run, confirm that the `api-tests` container actually executed."
                    ),
                    "After the run, open `target/cucumber/cucumber-html-reports/overview-features.html` or `target/surefire-reports/index.html`."
            );
            case LOCAL_SETUP, START_KAFKA_ONLY -> buildSetupAnswer(
                    intent == QuestionIntent.START_KAFKA_ONLY
                            ? "Use the Kafka-only Compose file when you want Kafka in Docker but keep the Node server and Maven on the host."
                            : "For hybrid local execution, start Kafka in Docker, run the Node server locally, then run Maven from the project root.",
                    List.of(
                            codeBlock("bash", "docker compose -f docker-compose.kafka.yml up -d"),
                            codeBlock("bash", SERVER_START_COMMAND),
                            codeBlock("bash", FULL_SUITE_COMMAND)
                    ),
                    chunks,
                    environmentReport,
                    List.of(
                            "In hybrid local mode, use `localhost:9092`. In the full Docker stack, containers use `kafka:9092` internally.",
                            "Run Maven from the project root so `pom.xml`, `config.properties`, and TestNG suites resolve correctly."
                    ),
                    "If Kafka tests still fail, ask: `Why can’t I run Kafka tests locally?`"
            );
            case RUN_NEGATIVE -> buildSetupAnswer(
                    "Use the `@Negative` tag to run the relationship and dependency validation scenarios only.",
                    List.of(codeBlock("bash", taggedRunCommand("@Negative"))),
                    chunks,
                    null,
                    List.of(
                            "Negative scenarios still need Kafka running because they verify that no matching event is published.",
                            "If you only start the server and do not run Maven, no Cucumber or Surefire reports will be created."
                    ),
                    "If you want one negative family only, ask about account, portfolio, transaction, or delete-specific scenarios."
            );
            case RUN_KAFKA -> buildSetupAnswer(
                    "Run Kafka scenarios by tag. The framework already has group tags for each entity and narrower tags for individual event scenarios.",
                    List.of(codeBlock("bash", buildKafkaRunCommand(question))),
                    chunks,
                    null,
                    List.of(
                            "Make sure the topic properties passed to Maven match the topics configured for the server process.",
                            "If a scenario times out waiting for Kafka, check the server console for `[AI-KAFKA-VALIDATOR][Kafka] Published ...` with the same entity id."
                    ),
                    "Ask `How do I run only transaction Kafka tests?` for the narrowest Kafka example."
            );
            case RERUN_FAILURES -> buildSetupAnswer(
                    "Use the rerun TestNG suite after a failed run. It consumes `target/rerun.txt` produced by the main suite.",
                    List.of(codeBlock("bash", "sh ./mvnw test -Dtestng.suite.file=testng-rerun.xml -DbaseURI=http://localhost:3000 -DkafkaBootstrapServers=localhost:9092 -DkafkaClientEventsTopic=client-events -DkafkaAccountEventsTopic=account-events -DkafkaPortfolioEventsTopic=portfolio-events -DkafkaTransactionEventsTopic=transaction-events")),
                    chunks,
                    null,
                    List.of(
                            "Run the main suite first so `target/rerun.txt` exists.",
                            "If the rerun suite does nothing, verify that the previous run actually produced failed scenarios."
                    ),
                    "If you want to analyze failures before rerunning, ask about the Failure Analysis Agent."
            );
            case REPORTS -> buildSetupAnswer(
                    "Reports are generated by the Maven test run and are written under `target/`.",
                    List.of(
                            codeBlock("bash", "open target/cucumber-report.html\nopen target/cucumber/cucumber-html-reports/overview-features.html\nopen target/surefire-reports/index.html\nopen target/surefire-reports/failure-analysis.html"),
                            codeBlock("powershell", "start target\\cucumber-report.html\nstart target\\cucumber\\cucumber-html-reports\\overview-features.html\nstart target\\surefire-reports\\index.html\nstart target\\surefire-reports\\failure-analysis.html")
                    ),
                    chunks,
                    environmentReport,
                    List.of(
                            "If you ran only `npm start`, you will see server logs but no Cucumber or Surefire reports.",
                            "If a report is empty, verify that Maven executed scenarios and that your tag filter matched at least one scenario."
                    ),
                    "If you need root-cause guidance for failed tests, run or open the Failure Analysis Agent output."
            );
            case RESET_DATA -> buildSetupAnswer(
                    "Runtime data is restored from `server/seed-data.json` into `server/clients.json`. The server works only with the runtime file.",
                    List.of(
                            codeBlock("bash", "cd server\nnpm run reset-data"),
                            codeBlock("bash", "cd server\nnpm start")
                    ),
                    chunks,
                    environmentReport,
                    List.of(
                            "The seed file should stay unchanged; tests and the server work against `clients.json`.",
                            "`npm start` already performs a reset before launching the server."
                    ),
                    "If reset still seems wrong, confirm that both `server/seed-data.json` and `server/clients.json` exist and are writable."
            );
            case FAILURE_AGENT -> buildSetupAnswer(
                    "The Failure Analysis Agent inspects failed execution artifacts and writes structured markdown and HTML reports under `target/`.",
                    List.of(
                            codeBlock("bash", "sh ./mvnw -q exec:java -Dexec.mainClass=com.analysis.failure.FailureAnalysisAgent"),
                            codeBlock("bash", "sh ./mvnw -q exec:java -Dexec.mainClass=com.analysis.failure.FailureAnalysisAgent -Dfailure.analysis.mode=latest")
                    ),
                    chunks,
                    null,
                    List.of(
                            "It relies on artifacts such as `target/cucumber.json`, `target/rerun.txt`, and `target/surefire-reports/TestSuite.txt`.",
                            "On a green run, it may report zero failures analyzed, which is expected."
                    ),
                    "The Failure Analysis Agent explains failures after execution. This onboarding agent explains setup, usage, navigation, and extension."
            );
            case DEMO_PATH -> buildSetupAnswer(
                    "For a short demo, run the chained cross-entity flow and then open the pretty report. If you want to highlight Kafka specifically, run one focused Kafka tag afterwards.",
                    List.of(
                            codeBlock("bash", taggedRunCommand("@CrossEntityE2E")),
                            codeBlock("bash", "open target/cucumber/cucumber-html-reports/overview-features.html")
                    ),
                    chunks,
                    null,
                    List.of(
                            "`@CrossEntityE2E` is easier to narrate than the full regression suite because it shows client, account, transaction, and Kafka linkage in one story.",
                            "For a Kafka-focused demo, `@KafkaTransactionData` is a good follow-up because it shows create, update, and delete event validation clearly."
                    ),
                    "If you want a narration of the message flow, ask: `How does Kafka publishing work in this framework?`"
            );
            case FRAMEWORK_OVERVIEW -> buildExplainAnswer(
                    "The framework combines a Java test layer, a Node mock backend, and Kafka validation in one runnable project. Cucumber steps call Java API classes, the Node service enforces business rules and publishes Kafka events, and Java consumers verify the resulting messages.",
                    chunks,
                    List.of(
                            "Cucumber + TestNG entrypoint: `src/test/java/com/runners/CukesRunner.java`",
                            "Java API layer: `src/test/java/com/api`",
                            "Kafka consumers and validators: `src/test/java/com/kafka`",
                            "Mock backend and publisher: `server/index.js` and `server/kafkaPublisher.js`"
                    ),
                    "The current framework supports full Docker execution, hybrid local execution, CRUD coverage across four related domains, Kafka event validation, negative relationship validation, chained business flows, seed/reset protection, and a separate Failure Analysis Agent.",
                    "If you later connect this to enterprise systems, you can keep the same testing layers while replacing the mock backend and single-broker Kafka with real environment endpoints and secure runtime configuration."
            );
            case KAFKA_FLOW -> buildExplainAnswer(
                    kafkaFlowExplanation(question),
                    chunks,
                    List.of(
                            "Server-side publishing trigger: `server/index.js`",
                            "Kafka producer and `producer.send(...)`: `server/kafkaPublisher.js`",
                            "Client consumer: `src/test/java/com/kafka/KafkaEventConsumer.java`",
                            "Entity consumer: `src/test/java/com/kafka/EntityKafkaEventConsumer.java`"
                    ),
                    "The Node backend publishes Kafka events only after successful CRUD operations. The Java side then waits for a matching event by business key and validates metadata and payload against the latest API response. Negative scenarios assert that failed operations do not publish the matching event.",
                    "In a real system, the same validation pattern can stay in place, but topic configuration, consumer isolation, security, and test-data correlation usually need stronger environment controls."
            );
            case PROJECT_NAVIGATION -> buildExplainAnswer(
                    projectNavigationExplanation(question),
                    chunks,
                    List.of(
                            "Feature files: `src/test/resources/features`",
                            "Step definitions: `src/test/java/com/step_defs`",
                            "API classes: `src/test/java/com/api`",
                            "Backend rules and publishing: `server/index.js` and `server/kafkaPublisher.js`"
                    ),
                    "Feature steps stay thin and delegate to API classes, validators, and Kafka helpers. Relationship validation and delete dependency rules are implemented on the Node backend side before Kafka publishing happens.",
                    "If you extend the project, keep the same split: feature -> step definition -> API class -> backend route -> Kafka validation."
            );
            case TROUBLESHOOT_KAFKA -> buildSetupAnswer(
                    "If Kafka tests fail locally, first verify that Kafka is running on `localhost:9092`, the server is pointing to the same broker, and the Java test properties match the actual topics.",
                    List.of(
                            codeBlock("bash", "docker compose -f docker-compose.kafka.yml up -d"),
                            codeBlock("bash", "curl http://localhost:3000/health")
                    ),
                    chunks,
                    environmentReport,
                    List.of(
                            "In hybrid local mode, the server and tests should use `localhost:9092`. Inside the full Docker stack they use `kafka:9092` internally.",
                            "If API calls succeed but no matching event is found, check the server console for `[AI-KAFKA-VALIDATOR][Kafka] Published ...` with the same entity id and event type.",
                            "The Java consumers search by key and event type, not by first message in the topic."
                    ),
                    "If the issue comes from a failed run, open `target/failure-analysis.md` or `target/surefire-reports/failure-analysis.html`."
            );
            case TROUBLESHOOT_SERVER -> buildSetupAnswer(
                    "If the API is not starting, verify Node.js and npm availability, make sure `npm install` has been run in `server/`, and confirm that `server/seed-data.json` can be copied into `server/clients.json` during startup.",
                    List.of(
                            codeBlock("bash", "cd server\nnpm install\nnpm start"),
                            codeBlock("bash", "curl http://localhost:3000/health")
                    ),
                    chunks,
                    environmentReport,
                    List.of(
                            "`npm start` runs `npm run reset-data && node index.js`, so missing seed files or write protection on `clients.json` can block startup.",
                            "In Docker, the server maps host port `3001` to container port `3000`. In hybrid local mode, the health endpoint is `http://localhost:3000/health`."
                    ),
                    "If the server is up but tests still fail, ask `Why are no Kafka events found?` or run the Failure Analysis Agent."
            );
            case TROUBLESHOOT_REPORTS -> buildSetupAnswer(
                    "If a report is empty, the most common cause is that only the Node server was started and Maven tests were not executed. Report artifacts are written by the Java run under `target/`.",
                    List.of(
                            codeBlock("bash", FULL_SUITE_COMMAND),
                            codeBlock("bash", "open target/cucumber/cucumber-html-reports/overview-features.html")
                    ),
                    chunks,
                    environmentReport,
                    List.of(
                            "If you use a tag filter, make sure it matches at least one scenario in the feature files.",
                            "On a green run, the Failure Analysis Agent may only generate a markdown file stating that no failures were found."
                    ),
                    "If you want only failed scenarios rerun, use `testng-rerun.xml` after the main suite creates `target/rerun.txt`."
            );
            case ENTERPRISE_KAFKA -> buildEnterpriseAnswer(
                    "The current framework uses a single Kafka broker, plain topic names, and environment-driven configuration through `config.properties`, Docker env vars, and `KafkaConfig`. The mock backend publishes events after successful CRUD operations and the Java side consumes them by business key.",
                    "A real Kafka deployment usually adds multiple brokers, secured listeners, authn/authz, environment-specific bootstrap servers, topic management outside the app, and stronger isolation between test and non-test traffic.",
                    "Keep the Java API layer and Kafka validators, but externalize broker, topic, auth, and environment settings. Add stage-specific config, dedicated test topics or filtered consumer strategy, and secure client properties for SASL/SSL where required.",
                    "The current framework does not implement Kafka auth, schema registry, or multi-broker failover logic. Those would be enterprise adaptations, not current features.",
                    "Start by moving broker and topic config fully into environment-specific properties, then add secured Kafka client configuration and CI-safe secrets handling.",
                    chunks
            );
            case ENTERPRISE_CICD -> buildEnterpriseAnswer(
                    "The framework already supports one-command Docker execution, selective tag execution through Maven properties, rerun support, and failure-analysis artifact generation under `target/`.",
                    "A real CI/CD setup usually needs pipeline stages for environment readiness, tagged suite execution, artifact publishing, and optional failure triage steps. Cloud runners may also need Docker-in-Docker or service containers.",
                    "Use the full Docker path for stable smoke jobs and tag-based Maven execution for targeted suites. Publish `target/` as build artifacts and run the Failure Analysis Agent after failed jobs to attach readable root-cause summaries.",
                    "The repository does not currently ship Jenkins, GitHub Actions, or Azure DevOps pipeline definitions, so pipeline wiring would be a new integration layer rather than an existing feature.",
                    "Start with one pipeline that runs `docker compose up --build --abort-on-container-exit --exit-code-from api-tests`, archives `target/`, and then split into tagged jobs if needed.",
                    chunks
            );
            case ENTERPRISE_BACKEND -> buildEnterpriseAnswer(
                    "The project currently talks to a Node.js mock backend built on json-server. Business rules, relationship validation, delete dependency checks, seed/reset, and Kafka publishing are all implemented in that mock service.",
                    "A real backend would likely persist to a database, enforce business rules in application services, and publish Kafka events through the production eventing path rather than the mock publisher in `server/kafkaPublisher.js`.",
                    "Keep the Java Cucumber, API, and Kafka validation layers. Replace the mock service base URI and topic configuration with real environment values, and provision prerequisite data through APIs, fixtures, or seeded environments instead of local JSON files.",
                    "The current framework assumes deterministic control over the backend and seed data. A real shared environment may need stronger isolation, cleanup, and tenancy rules.",
                    "Start by pointing one existing entity flow at a real test environment, then keep the same validation pattern while replacing the mock data setup strategy with environment-safe fixtures or helper APIs.",
                    chunks
            );
            case ENTERPRISE_DATABASE -> buildEnterpriseAnswer(
                    "The current project does not connect directly to a database. Runtime data is file-backed through `server/clients.json`, and reset is driven by copying `server/seed-data.json` into the runtime file.",
                    "A real environment would usually provision test data through APIs, seed jobs, database fixtures, ephemeral schemas, or dedicated integration-test datasets instead of overwriting local JSON files.",
                    "Keep the test orchestration layer independent of the database. Prefer environment-safe data setup through APIs or dedicated fixture services, and only use direct DB access when it is required for verification or provisioning and approved by the team.",
                    "The current framework does not include JDBC, ORM, or migration-based provisioning. Any DB integration would be an extension, not an existing capability.",
                    "Choose one repeatable test-data strategy first: API seeding, fixture service, or isolated DB schema per run. Then wire it into setup hooks or pre-test jobs rather than scattering DB calls through step definitions.",
                    chunks
            );
            case UNKNOWN -> buildExplainAnswer(
                    "I could not map your question to one narrow workflow, so I searched the project knowledge base and pulled the most relevant framework sources.",
                    chunks,
                    List.of(
                            "README and docs for setup, execution, and reporting",
                            "Step definitions and API classes for test orchestration",
                            "Node backend and Kafka publisher for business rules and event flow"
                    ),
                    "Current framework behavior should be derived from the referenced files first. If your question is broader, I can still give guidance, but I will separate current implementation from best-practice recommendations.",
                    "If you want a more targeted answer, ask a concrete question such as `How do I run only negative scenarios?` or `How would I adapt this for a real Kafka cluster?`"
            );
        };
    }

    private boolean needsEnvironmentChecks(QuestionIntent intent) {
        return switch (intent) {
            case QUICK_START, DOCKER_SETUP, LOCAL_SETUP, START_KAFKA_ONLY, REPORTS, RESET_DATA,
                    TROUBLESHOOT_KAFKA, TROUBLESHOOT_SERVER, TROUBLESHOOT_REPORTS -> true;
            default -> false;
        };
    }

    private String buildSetupAnswer(String directAnswer, List<String> commands, List<ProjectChunk> chunks,
                                    EnvironmentReport environmentReport, List<String> mistakes, String nextStep) {
        StringBuilder answer = new StringBuilder();
        section(answer, "1. Direct answer", directAnswer);
        section(answer, "2. Exact steps / commands", String.join(System.lineSeparator() + System.lineSeparator(), commands));
        if (environmentReport != null) {
            section(answer, "Environment checks", formatEnvironmentReport(environmentReport));
        }
        section(answer, "3. Relevant project files", formatRelevantFiles(chunks));
        section(answer, "4. Common mistakes to avoid", formatBullets(mistakes));
        section(answer, "5. Optional next step", nextStep);
        return answer.toString().trim();
    }

    private String buildExplainAnswer(String explanation, List<ProjectChunk> chunks, List<String> files,
                                      String currentBehavior, String enterpriseScaling) {
        StringBuilder answer = new StringBuilder();
        section(answer, "1. Short explanation", explanation);
        section(answer, "2. Relevant files/classes", formatBullets(files) + System.lineSeparator() + formatRelevantFiles(chunks));
        section(answer, "3. How the current framework does it", currentBehavior);
        section(answer, "4. How this would scale to enterprise if asked", enterpriseScaling);
        return answer.toString().trim();
    }

    private String buildEnterpriseAnswer(String currentBehavior, String changes, String integration,
                                         String constraints, String nextSteps, List<ProjectChunk> chunks) {
        StringBuilder answer = new StringBuilder();
        section(answer, "1. Current framework behavior", currentBehavior);
        section(answer, "2. What would change in a real system", changes);
        section(answer, "3. Recommended integration pattern", integration);
        section(answer, "4. Constraints / assumptions", constraints);
        section(answer, "5. Safe next steps", nextSteps);
        section(answer, "Relevant project files", formatRelevantFiles(chunks));
        return answer.toString().trim();
    }

    private String buildKafkaRunCommand(String question) {
        String normalized = question.toLowerCase(Locale.ROOT);
        String tags = "@KafkaClientData or @KafkaAccountData or @KafkaPortfolioData or @KafkaTransactionData";
        if (normalized.contains("transaction")) {
            tags = "@KafkaTransactionData";
        } else if (normalized.contains("account")) {
            tags = "@KafkaAccountData";
        } else if (normalized.contains("portfolio")) {
            tags = "@KafkaPortfolioData";
        } else if (normalized.contains("client")) {
            tags = "@KafkaClientData";
        }
        return taggedRunCommand(tags);
    }

    private String taggedRunCommand(String tags) {
        return "sh ./mvnw clean test -Dtestng.suite.file=testng.xml -Dcucumber.filter.tags=\"" + tags
                + "\" -DbaseURI=http://localhost:3000 -DkafkaBootstrapServers=localhost:9092 -DkafkaClientEventsTopic=client-events -DkafkaAccountEventsTopic=account-events -DkafkaPortfolioEventsTopic=portfolio-events -DkafkaTransactionEventsTopic=transaction-events";
    }

    private String kafkaFlowExplanation(String question) {
        String normalized = question.toLowerCase(Locale.ROOT);
        if (normalized.contains("account") || normalized.contains("portfolio") || normalized.contains("transaction")) {
            return "For account, portfolio, and transaction flows, the Node backend registers entity routes in `server/index.js`, validates business rules, then calls `publishEntityEvent(...)`. The actual Kafka send happens in `server/kafkaPublisher.js` through `producer.send(...)`. On the Java side, `EntityKafkaEventConsumer` waits for the matching event by `entityId` and `eventType`, and `EntityKafkaEventValidator` compares metadata and payload against the latest API response.";
        }
        return "Client events are published from `server/index.js` through `publishClientEvent(...)`, while account, portfolio, and transaction events are published through `publishEntityEvent(...)`. The actual Kafka send is handled in `server/kafkaPublisher.js`. Java tests start the appropriate consumer, wait for a matching event by business key, and then validate both metadata and payload against the API response.";
    }

    private String projectNavigationExplanation(String question) {
        String normalized = question.toLowerCase(Locale.ROOT);
        if (normalized.contains("negative") || normalized.contains("relationship")) {
            return "Negative relationship coverage is split between backend validation and test coverage. The rules are implemented in `server/index.js`, while the scenarios live in `src/test/resources/features/NegativeValidationE2E.feature` and the orchestration logic lives in `src/test/java/com/step_defs/BusinessValidationStepDefs.java`.";
        }
        if (normalized.contains("cross-entity") || normalized.contains("business flow")) {
            return "The chained client-account-transaction demo flow lives in `src/test/resources/features/CrossEntityBusinessFlow.feature` and is executed through `BusinessValidationStepDefs` plus the existing API and Kafka helpers.";
        }
        if (normalized.contains("failure")) {
            return "Failure analysis logic lives under `src/main/java/com/analysis/failure`, while the automatic TestNG hook is in `src/test/java/com/analysis/failure/FailureAnalysisExecutionListener.java`.";
        }
        return "The project is organized by responsibility: feature files under `src/test/resources/features`, orchestration in `src/test/java/com/step_defs`, request logic in `src/test/java/com/api`, Kafka support in `src/test/java/com/kafka`, backend logic in `server/`, and agent utilities under `src/main/java/com/analysis`.";
    }

    private void section(StringBuilder answer, String heading, String content) {
        if (content == null || content.isBlank()) {
            return;
        }
        if (!answer.isEmpty()) {
            answer.append(System.lineSeparator()).append(System.lineSeparator());
        }
        answer.append(heading).append(System.lineSeparator());
        answer.append(content);
    }

    private String formatEnvironmentReport(EnvironmentReport report) {
        List<String> lines = new ArrayList<>();
        for (EnvironmentCheck check : report.checks()) {
            lines.add("- [" + check.status() + "] " + check.name() + ": " + check.detail());
        }
        return String.join(System.lineSeparator(), lines);
    }

    private String formatRelevantFiles(List<ProjectChunk> chunks) {
        if (chunks == null || chunks.isEmpty()) {
            return "- No strongly matching framework sources were retrieved for this question.";
        }

        Set<String> lines = new LinkedHashSet<>();
        for (ProjectChunk chunk : chunks) {
            lines.add("- `" + chunk.location() + "` - " + chunk.title());
            if (lines.size() >= 6) {
                break;
            }
        }
        return String.join(System.lineSeparator(), lines);
    }

    private String formatBullets(List<String> lines) {
        return lines.stream()
                .map(line -> "- " + line)
                .reduce((left, right) -> left + System.lineSeparator() + right)
                .orElse("- None");
    }

    private String codeBlock(String language, String content) {
        return "```" + language + System.lineSeparator() + content.stripTrailing() + System.lineSeparator() + "```";
    }
}
