package com.analysis.failure;

public enum FailureCategory {
    API_ASSERTION_FAILURE,
    KAFKA_EVENT_NOT_FOUND,
    KAFKA_PAYLOAD_MISMATCH,
    RELATIONSHIP_VALIDATION_FAILURE,
    DELETE_DEPENDENCY_FAILURE,
    CONFIGURATION_ERROR,
    INFRASTRUCTURE_ERROR,
    TEST_DATA_ISSUE,
    UNKNOWN
}
